import { useState, useEffect } from "react";
import axios from "axios";
import "./LandingPage.css";

const API = process.env.REACT_APP_API_URL || "http://localhost:8000";

function TosModal({ onAgree, onDecline }) {
  return (
    <div className="modal-overlay">
      <div className="modal-card">
        <div className="modal-header">
          <h2>Terms of Service</h2>
        </div>

        <div className="modal-body">
          <p className="tos-date">Last updated: May 2026</p>

          <div className="tos-section">
            <h3>1. Acceptance</h3>
            <p>
              By using the DLSU Handbook Assistant, you agree to these terms.
              If you do not agree, please do not use this service.
            </p>
          </div>

          <div className="tos-section">
            <h3>2. About This Service</h3>
            <p>
              This is an <strong style={{ color: "#ececec" }}>unofficial, student-made AI assistant</strong> designed
              to help users navigate the DLSU Student Handbook 2021–2025. It is
              not affiliated with, endorsed by, or officially connected to De La
              Salle University or any of its offices.
            </p>
          </div>

          <div className="tos-section">
            <h3>3. Accuracy Disclaimer</h3>
            <ul>
              <li>Responses are generated by AI and may be incomplete, outdated, or incorrect.</li>
              <li>Do not rely solely on this assistant for academic, disciplinary, or legal decisions.</li>
              <li>Always verify information with the official DLSU Student Handbook or consult the SDFO and relevant university offices.</li>
            </ul>
          </div>

          <div className="tos-section">
            <h3>4. Acceptable Use</h3>
            <p>You agree not to use this service to:</p>
            <ul>
              <li>Submit harmful, abusive, or offensive content</li>
              <li>Attempt to manipulate or jailbreak the AI</li>
              <li>Use outputs for academic dishonesty</li>
            </ul>
          </div>

          <div className="tos-section">
            <h3>5. Privacy</h3>
            <p>
              This assistant does not collect personal information. Conversation
              data may be used to improve the service but is not linked to your
              identity.
            </p>
          </div>

          <div className="tos-section">
            <h3>6. Limitation of Liability</h3>
            <p>
              The creator of this tool is not responsible for any consequences
              resulting from reliance on AI-generated responses.
            </p>
          </div>

          <div className="tos-section">
            <h3>7. Changes</h3>
            <p>
              These terms may be updated at any time. Continued use of the
              service implies acceptance of any changes.
            </p>
          </div>
        </div>

        <div className="modal-footer">
          <button className="modal-agree-btn" onClick={onAgree}>
            I Agree — Start Chatting →
          </button>
          <button className="modal-decline-btn" onClick={onDecline}>
            Decline
          </button>
        </div>
      </div>
    </div>
  );
}

export default function LandingPage({ onStart }) {
  const [stats, setStats] = useState(null);
  const [showTos, setShowTos] = useState(false);

  useEffect(() => {
    axios.get(`${API}/stats`)
      .then(r => setStats(r.data))
      .catch(() => {});
  }, []);

  return (
    <div className="landing">
      {showTos && (
        <TosModal
          onAgree={onStart}
          onDecline={() => setShowTos(false)}
        />
      )}

      <div className="landing-card">
        <div className="landing-logo">La</div>
        <h1 className="landing-title">DLSU Handbook Assistant</h1>
        <p className="landing-subtitle">
          Your AI guide to the DLSU Student Handbook 2021-2025
        </p>

        <div className="landing-stats">
          <div className="stat-item">
            <div className="stat-number">
              {stats ? stats.total_visits.toLocaleString() : "—"}
            </div>
            <div className="stat-label">Total visits</div>
          </div>
          <div className="stat-divider" />
          <div className="stat-item">
            <div className="stat-number">
              {stats ? stats.total_questions.toLocaleString() : "—"}
            </div>
            <div className="stat-label">Questions answered</div>
          </div>
        </div>

        <div className="landing-warning">
          <span className="landing-warning-text">
            This assistant is AI-powered and may give inaccurate or incomplete
            answers. Always verify with the official handbook or consult the
            SDFO directly.
          </span>
        </div>

        <button className="landing-btn" onClick={() => setShowTos(true)}>
          Start chatting →
        </button>

        <p className="landing-disclaimer">
          AI-generated responses based on DLSU Student Handbook 2021-2025.
This is an unofficial student project. Not affiliated with DLSU.
Always verify important information with the SDFO or relevant office.
        </p>
      </div>
    </div>
  );
}